volumes:
  sqlite_data:

services:
  validator:
    init: true
    image: public.ecr.aws/c9f7n4n0/patrol/validator:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      ENABLE_AUTO_UPDATE: 1
      # WALLET_NAME: my_wallet
      # HOTKEY_NAME: my_hotkey
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      - sqlite_data:/var/patrol/sqlite

